server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xpmxf4/spring-cloud-config.git
#          username: [id], -> file ?? ????
#          password: [pwd]
#          uri: file:///Users/xpmxf4/desktop/develop/spring-cloud/git-local-repo