server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xpmxf4/spring-cloud-config.git
#          username: [id], -> file ?? ????
#          password: [pwd]
#          uri: file:///Users/xpmxf4/desktop/develop/spring-cloud/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh 